version: "3.7"

services:
  fluent-bit:
    image: public.ecr.aws/aws-observability/aws-for-fluent-bit:latest
    ports:
      - 24224:24224
    environment:
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
      AWS_SESSION_TOKEN: '${AWS_SESSION_TOKEN}'
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf